name: neura_rendering
description: Shared Flame rendering for Neura applications.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.14.0-10.0.dev

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.37.0
  neura_assets:
    path: ../neura_assets
  neura_world:
    path: ../neura_world

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: {}
