// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blocked_at_point`, `build`, `cell_for`, `center`, `coordinates`, `distance_squared`, `distance_to_segment`, `find_path`, `heuristic`, `nearest_open`, `path_result`, `polygon_contains_or_near`, `rasterize_bounds`, `rasterize_polygon`, `rasterize_stroke`, `reconstruct`, `segment_walkable`, `smooth_visible_segments`, `snapshot`, `worlds`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NavigationWorld`, `OpenNode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`

Future<NativeNavigationWorldCreated> nativeNavigationWorldCreate({
  required NativeNavigationWorldInput input,
}) => RustLib.instance.api.crateApiNativeNavigationWorldCreate(input: input);

Future<NativeNavigationSnapshot> nativeNavigationWorldReplace({
  required int handle,
  required NativeNavigationWorldInput input,
}) => RustLib.instance.api.crateApiNativeNavigationWorldReplace(
  handle: handle,
  input: input,
);

Future<NativeNavigationPathResult> nativeNavigationWorldFindPath({
  required int handle,
  required NativeNavigationPoint start,
  required NativeNavigationPoint destination,
}) => RustLib.instance.api.crateApiNativeNavigationWorldFindPath(
  handle: handle,
  start: start,
  destination: destination,
);

bool nativeNavigationWorldClose({required int handle}) =>
    RustLib.instance.api.crateApiNativeNavigationWorldClose(handle: handle);

class NativeNavigationPathResult {
  final List<NativeNavigationPoint> points;
  final int expandedNodes;
  final int elapsedMicros;

  const NativeNavigationPathResult({
    required this.points,
    required this.expandedNodes,
    required this.elapsedMicros,
  });

  @override
  int get hashCode =>
      points.hashCode ^ expandedNodes.hashCode ^ elapsedMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationPathResult &&
          runtimeType == other.runtimeType &&
          points == other.points &&
          expandedNodes == other.expandedNodes &&
          elapsedMicros == other.elapsedMicros;
}

class NativeNavigationPoint {
  final double x;
  final double y;

  const NativeNavigationPoint({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class NativeNavigationPolygon {
  final List<NativeNavigationPoint> points;

  const NativeNavigationPolygon({required this.points});

  @override
  int get hashCode => points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationPolygon &&
          runtimeType == other.runtimeType &&
          points == other.points;
}

class NativeNavigationSnapshot {
  final int columns;
  final int rows;
  final Uint8List blockedCells;

  const NativeNavigationSnapshot({
    required this.columns,
    required this.rows,
    required this.blockedCells,
  });

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode ^ blockedCells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationSnapshot &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows &&
          blockedCells == other.blockedCells;
}

class NativeNavigationTerrainStroke {
  final List<NativeNavigationPoint> points;
  final double radius;
  final bool blocked;

  const NativeNavigationTerrainStroke({
    required this.points,
    required this.radius,
    required this.blocked,
  });

  @override
  int get hashCode => points.hashCode ^ radius.hashCode ^ blocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationTerrainStroke &&
          runtimeType == other.runtimeType &&
          points == other.points &&
          radius == other.radius &&
          blocked == other.blocked;
}

class NativeNavigationWorldCreated {
  final int handle;
  final NativeNavigationSnapshot snapshot;

  const NativeNavigationWorldCreated({
    required this.handle,
    required this.snapshot,
  });

  @override
  int get hashCode => handle.hashCode ^ snapshot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationWorldCreated &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          snapshot == other.snapshot;
}

class NativeNavigationWorldInput {
  final double width;
  final double height;
  final double cellSize;
  final double actorRadius;
  final bool baseBlocked;
  final List<NativeNavigationTerrainStroke> terrainStrokes;
  final List<NativeNavigationPolygon> objectColliders;

  const NativeNavigationWorldInput({
    required this.width,
    required this.height,
    required this.cellSize,
    required this.actorRadius,
    required this.baseBlocked,
    required this.terrainStrokes,
    required this.objectColliders,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      cellSize.hashCode ^
      actorRadius.hashCode ^
      baseBlocked.hashCode ^
      terrainStrokes.hashCode ^
      objectColliders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeNavigationWorldInput &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          cellSize == other.cellSize &&
          actorRadius == other.actorRadius &&
          baseBlocked == other.baseBlocked &&
          terrainStrokes == other.terrainStrokes &&
          objectColliders == other.objectColliders;
}
