// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NativeNavigationPoint dco_decode_box_autoadd_native_navigation_point(
    dynamic raw,
  );

  @protected
  NativeNavigationWorldInput
  dco_decode_box_autoadd_native_navigation_world_input(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<NativeNavigationPoint> dco_decode_list_native_navigation_point(
    dynamic raw,
  );

  @protected
  List<NativeNavigationPolygon> dco_decode_list_native_navigation_polygon(
    dynamic raw,
  );

  @protected
  List<NativeNavigationTerrainStroke>
  dco_decode_list_native_navigation_terrain_stroke(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NativeNavigationPathResult dco_decode_native_navigation_path_result(
    dynamic raw,
  );

  @protected
  NativeNavigationPoint dco_decode_native_navigation_point(dynamic raw);

  @protected
  NativeNavigationPolygon dco_decode_native_navigation_polygon(dynamic raw);

  @protected
  NativeNavigationSnapshot dco_decode_native_navigation_snapshot(dynamic raw);

  @protected
  NativeNavigationTerrainStroke dco_decode_native_navigation_terrain_stroke(
    dynamic raw,
  );

  @protected
  NativeNavigationWorldCreated dco_decode_native_navigation_world_created(
    dynamic raw,
  );

  @protected
  NativeNavigationWorldInput dco_decode_native_navigation_world_input(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NativeNavigationPoint sse_decode_box_autoadd_native_navigation_point(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationWorldInput
  sse_decode_box_autoadd_native_navigation_world_input(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<NativeNavigationPoint> sse_decode_list_native_navigation_point(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeNavigationPolygon> sse_decode_list_native_navigation_polygon(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeNavigationTerrainStroke>
  sse_decode_list_native_navigation_terrain_stroke(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NativeNavigationPathResult sse_decode_native_navigation_path_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationPoint sse_decode_native_navigation_point(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationPolygon sse_decode_native_navigation_polygon(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationSnapshot sse_decode_native_navigation_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationTerrainStroke sse_decode_native_navigation_terrain_stroke(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationWorldCreated sse_decode_native_navigation_world_created(
    SseDeserializer deserializer,
  );

  @protected
  NativeNavigationWorldInput sse_decode_native_navigation_world_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_native_navigation_point(
    NativeNavigationPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_navigation_world_input(
    NativeNavigationWorldInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_native_navigation_point(
    List<NativeNavigationPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_navigation_polygon(
    List<NativeNavigationPolygon> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_navigation_terrain_stroke(
    List<NativeNavigationTerrainStroke> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_path_result(
    NativeNavigationPathResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_point(
    NativeNavigationPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_polygon(
    NativeNavigationPolygon self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_snapshot(
    NativeNavigationSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_terrain_stroke(
    NativeNavigationTerrainStroke self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_world_created(
    NativeNavigationWorldCreated self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_navigation_world_input(
    NativeNavigationWorldInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
