// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 438456183;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'neura_world_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiNativeNavigationWorldClose({required int handle});

  Future<NativeNavigationWorldCreated> crateApiNativeNavigationWorldCreate({
    required NativeNavigationWorldInput input,
  });

  Future<NativeNavigationPathResult> crateApiNativeNavigationWorldFindPath({
    required int handle,
    required NativeNavigationPoint start,
    required NativeNavigationPoint destination,
  });

  Future<NativeNavigationSnapshot> crateApiNativeNavigationWorldReplace({
    required int handle,
    required NativeNavigationWorldInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiNativeNavigationWorldClose({required int handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNativeNavigationWorldCloseConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativeNavigationWorldCloseConstMeta =>
      const TaskConstMeta(
        debugName: "native_navigation_world_close",
        argNames: ["handle"],
      );

  @override
  Future<NativeNavigationWorldCreated> crateApiNativeNavigationWorldCreate({
    required NativeNavigationWorldInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_navigation_world_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_navigation_world_created,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativeNavigationWorldCreateConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativeNavigationWorldCreateConstMeta =>
      const TaskConstMeta(
        debugName: "native_navigation_world_create",
        argNames: ["input"],
      );

  @override
  Future<NativeNavigationPathResult> crateApiNativeNavigationWorldFindPath({
    required int handle,
    required NativeNavigationPoint start,
    required NativeNavigationPoint destination,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_box_autoadd_native_navigation_point(start, serializer);
          sse_encode_box_autoadd_native_navigation_point(
            destination,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_navigation_path_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativeNavigationWorldFindPathConstMeta,
        argValues: [handle, start, destination],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativeNavigationWorldFindPathConstMeta =>
      const TaskConstMeta(
        debugName: "native_navigation_world_find_path",
        argNames: ["handle", "start", "destination"],
      );

  @override
  Future<NativeNavigationSnapshot> crateApiNativeNavigationWorldReplace({
    required int handle,
    required NativeNavigationWorldInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          sse_encode_box_autoadd_native_navigation_world_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_navigation_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativeNavigationWorldReplaceConstMeta,
        argValues: [handle, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativeNavigationWorldReplaceConstMeta =>
      const TaskConstMeta(
        debugName: "native_navigation_world_replace",
        argNames: ["handle", "input"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NativeNavigationPoint dco_decode_box_autoadd_native_navigation_point(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_navigation_point(raw);
  }

  @protected
  NativeNavigationWorldInput
  dco_decode_box_autoadd_native_navigation_world_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_navigation_world_input(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<NativeNavigationPoint> dco_decode_list_native_navigation_point(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_navigation_point)
        .toList();
  }

  @protected
  List<NativeNavigationPolygon> dco_decode_list_native_navigation_polygon(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_navigation_polygon)
        .toList();
  }

  @protected
  List<NativeNavigationTerrainStroke>
  dco_decode_list_native_navigation_terrain_stroke(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_navigation_terrain_stroke)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NativeNavigationPathResult dco_decode_native_navigation_path_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeNavigationPathResult(
      points: dco_decode_list_native_navigation_point(arr[0]),
      expandedNodes: dco_decode_u_32(arr[1]),
      elapsedMicros: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  NativeNavigationPoint dco_decode_native_navigation_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeNavigationPoint(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  NativeNavigationPolygon dco_decode_native_navigation_polygon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NativeNavigationPolygon(
      points: dco_decode_list_native_navigation_point(arr[0]),
    );
  }

  @protected
  NativeNavigationSnapshot dco_decode_native_navigation_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeNavigationSnapshot(
      columns: dco_decode_u_32(arr[0]),
      rows: dco_decode_u_32(arr[1]),
      blockedCells: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  NativeNavigationTerrainStroke dco_decode_native_navigation_terrain_stroke(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeNavigationTerrainStroke(
      points: dco_decode_list_native_navigation_point(arr[0]),
      radius: dco_decode_f_64(arr[1]),
      blocked: dco_decode_bool(arr[2]),
    );
  }

  @protected
  NativeNavigationWorldCreated dco_decode_native_navigation_world_created(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeNavigationWorldCreated(
      handle: dco_decode_u_32(arr[0]),
      snapshot: dco_decode_native_navigation_snapshot(arr[1]),
    );
  }

  @protected
  NativeNavigationWorldInput dco_decode_native_navigation_world_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NativeNavigationWorldInput(
      width: dco_decode_f_64(arr[0]),
      height: dco_decode_f_64(arr[1]),
      cellSize: dco_decode_f_64(arr[2]),
      actorRadius: dco_decode_f_64(arr[3]),
      baseBlocked: dco_decode_bool(arr[4]),
      terrainStrokes: dco_decode_list_native_navigation_terrain_stroke(arr[5]),
      objectColliders: dco_decode_list_native_navigation_polygon(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NativeNavigationPoint sse_decode_box_autoadd_native_navigation_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_navigation_point(deserializer));
  }

  @protected
  NativeNavigationWorldInput
  sse_decode_box_autoadd_native_navigation_world_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_navigation_world_input(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<NativeNavigationPoint> sse_decode_list_native_navigation_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeNavigationPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_navigation_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeNavigationPolygon> sse_decode_list_native_navigation_polygon(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeNavigationPolygon>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_navigation_polygon(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeNavigationTerrainStroke>
  sse_decode_list_native_navigation_terrain_stroke(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeNavigationTerrainStroke>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_navigation_terrain_stroke(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NativeNavigationPathResult sse_decode_native_navigation_path_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_points = sse_decode_list_native_navigation_point(deserializer);
    var var_expandedNodes = sse_decode_u_32(deserializer);
    var var_elapsedMicros = sse_decode_u_32(deserializer);
    return NativeNavigationPathResult(
      points: var_points,
      expandedNodes: var_expandedNodes,
      elapsedMicros: var_elapsedMicros,
    );
  }

  @protected
  NativeNavigationPoint sse_decode_native_navigation_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    return NativeNavigationPoint(x: var_x, y: var_y);
  }

  @protected
  NativeNavigationPolygon sse_decode_native_navigation_polygon(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_points = sse_decode_list_native_navigation_point(deserializer);
    return NativeNavigationPolygon(points: var_points);
  }

  @protected
  NativeNavigationSnapshot sse_decode_native_navigation_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columns = sse_decode_u_32(deserializer);
    var var_rows = sse_decode_u_32(deserializer);
    var var_blockedCells = sse_decode_list_prim_u_8_strict(deserializer);
    return NativeNavigationSnapshot(
      columns: var_columns,
      rows: var_rows,
      blockedCells: var_blockedCells,
    );
  }

  @protected
  NativeNavigationTerrainStroke sse_decode_native_navigation_terrain_stroke(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_points = sse_decode_list_native_navigation_point(deserializer);
    var var_radius = sse_decode_f_64(deserializer);
    var var_blocked = sse_decode_bool(deserializer);
    return NativeNavigationTerrainStroke(
      points: var_points,
      radius: var_radius,
      blocked: var_blocked,
    );
  }

  @protected
  NativeNavigationWorldCreated sse_decode_native_navigation_world_created(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_snapshot = sse_decode_native_navigation_snapshot(deserializer);
    return NativeNavigationWorldCreated(
      handle: var_handle,
      snapshot: var_snapshot,
    );
  }

  @protected
  NativeNavigationWorldInput sse_decode_native_navigation_world_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_cellSize = sse_decode_f_64(deserializer);
    var var_actorRadius = sse_decode_f_64(deserializer);
    var var_baseBlocked = sse_decode_bool(deserializer);
    var var_terrainStrokes = sse_decode_list_native_navigation_terrain_stroke(
      deserializer,
    );
    var var_objectColliders = sse_decode_list_native_navigation_polygon(
      deserializer,
    );
    return NativeNavigationWorldInput(
      width: var_width,
      height: var_height,
      cellSize: var_cellSize,
      actorRadius: var_actorRadius,
      baseBlocked: var_baseBlocked,
      terrainStrokes: var_terrainStrokes,
      objectColliders: var_objectColliders,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_native_navigation_point(
    NativeNavigationPoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_navigation_point(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_navigation_world_input(
    NativeNavigationWorldInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_navigation_world_input(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_native_navigation_point(
    List<NativeNavigationPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_navigation_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_navigation_polygon(
    List<NativeNavigationPolygon> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_navigation_polygon(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_navigation_terrain_stroke(
    List<NativeNavigationTerrainStroke> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_navigation_terrain_stroke(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_native_navigation_path_result(
    NativeNavigationPathResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_navigation_point(self.points, serializer);
    sse_encode_u_32(self.expandedNodes, serializer);
    sse_encode_u_32(self.elapsedMicros, serializer);
  }

  @protected
  void sse_encode_native_navigation_point(
    NativeNavigationPoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
  }

  @protected
  void sse_encode_native_navigation_polygon(
    NativeNavigationPolygon self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_navigation_point(self.points, serializer);
  }

  @protected
  void sse_encode_native_navigation_snapshot(
    NativeNavigationSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.columns, serializer);
    sse_encode_u_32(self.rows, serializer);
    sse_encode_list_prim_u_8_strict(self.blockedCells, serializer);
  }

  @protected
  void sse_encode_native_navigation_terrain_stroke(
    NativeNavigationTerrainStroke self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_navigation_point(self.points, serializer);
    sse_encode_f_64(self.radius, serializer);
    sse_encode_bool(self.blocked, serializer);
  }

  @protected
  void sse_encode_native_navigation_world_created(
    NativeNavigationWorldCreated self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_native_navigation_snapshot(self.snapshot, serializer);
  }

  @protected
  void sse_encode_native_navigation_world_input(
    NativeNavigationWorldInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_f_64(self.cellSize, serializer);
    sse_encode_f_64(self.actorRadius, serializer);
    sse_encode_bool(self.baseBlocked, serializer);
    sse_encode_list_native_navigation_terrain_stroke(
      self.terrainStrokes,
      serializer,
    );
    sse_encode_list_native_navigation_polygon(self.objectColliders, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
